import { BoardColFigure, DrawerBoard } from "../types";

// const generateRow = (start: number, end: number) => {
//   const row = [];

//   for (let i = start; i <= end; i++) {
//     row.push({
//       label: i.toString(),
//       value: i,
//     });
//   }

//   return row;
// };

const widthSquare = 17;
const widthRectangle = 61;

const mainRowB = [
  {
    label: "BA",
    value: 0,
    height: 246,
    x: 0,
    col: [
      {
        label: "BAA",
        value: 0,
        height: 0,
        y: 0,
        row: [
          {
            label: "BAAA",
            value: 0,
            height: 71,
            y: 0,
            col: [
              {
                key: 49,
                label: "A",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
                hoverPoints: ["A"],
              },
              {
                key: 3,
                label: "B",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 50,
                label: "C",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 6,
                label: "D",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 51,
                label: "E",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 9,
                label: "F",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 52,
                label: "G",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 12,
                label: "H",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 53,
                label: "I",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 15,
                label: "J",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 54,
                label: "K",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 18,
                label: "L",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 55,
                label: "M",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 21,
                label: "N",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 56,
                label: "O",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 24,
                label: "P",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 57,
                label: "Q",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 27,
                label: "R",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 58,
                label: "S",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 30,
                label: "T",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 59,
                label: "U",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 33,
                label: "V",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 60,
                label: "W",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 36,
                label: "X",
                value: 0,
                width: widthRectangle + 14,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAB",
            value: 0,
            y: 0,
            col: [
              {
                key: 61,
                label: "Y",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 62,
                label: "Z",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 63,
                label: "AA",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 64,
                label: "AB",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 65,
                label: "AC",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 66,
                label: "AD",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 67,
                label: "AE",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 68,
                label: "AF",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 69,
                label: "AG",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 70,
                label: "AH",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 71,
                label: "AI",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 72,
                label: "AJ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 73,
                label: "AK",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 74,
                label: "AL",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 75,
                label: "AM",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 76,
                label: "AN",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 77,
                label: "AO",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 78,
                label: "AP",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 79,
                label: "AQ",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 80,
                label: "AR",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 81,
                label: "AS",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 82,
                label: "AT",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 83,
                label: "AU",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 84,
                label: "AV",
                value: 0,
                width: widthRectangle + 14,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAC",
            value: 0,
            y: 0,
            col: [
              {
                key: 85,
                label: "AW",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 2,
                label: "AX",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 86,
                label: "AY",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 5,
                label: "AZ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 87,
                label: "BA",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 8,
                label: "BB",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 88,
                label: "BC",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 11,
                label: "BD",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 89,
                label: "BE",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 14,
                label: "BF",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 90,
                label: "BG",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 17,
                label: "BH",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 91,
                label: "BI",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 20,
                label: "BJ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 92,
                label: "BK",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 23,
                label: "BL",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 93,
                label: "BM",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 26,
                label: "BN",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 94,
                label: "BO",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 29,
                label: "BP",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 95,
                label: "BQ",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 32,
                label: "BR",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 96,
                label: "BS",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 35,
                label: "BT",
                value: 0,
                width: widthRectangle + 14,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAD",
            value: 0,
            y: 0,
            col: [
              {
                key: 97,
                label: "BU",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 98,
                label: "BV",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 99,
                label: "BW",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 100,
                label: "BX",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 101,
                label: "BY",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 102,
                label: "BZ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 103,
                label: "CA",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 104,
                label: "CB",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 105,
                label: "CC",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 106,
                label: "CD",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 107,
                label: "CE",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 108,
                label: "CF",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 109,
                label: "CG",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 110,
                label: "CH",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 111,
                label: "CI",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 112,
                label: "CJ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 113,
                label: "CK",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 114,
                label: "CL",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 115,
                label: "CM",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 116,
                label: "CN",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 117,
                label: "CO",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 118,
                label: "CP",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 119,
                label: "CQ",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 120,
                label: "CR",
                value: 0,
                width: widthRectangle + 14,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAE",
            value: 0,
            y: 0,
            col: [
              {
                key: 121,
                label: "CS",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 1,
                label: "CT",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 122,
                label: "CU",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 4,
                label: "CV",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 123,
                label: "CW",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 7,
                label: "CX",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 124,
                label: "CY",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 10,
                label: "CZ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 125,
                label: "DA",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 13,
                label: "DB",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 126,
                label: "DC",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 16,
                label: "DD",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 127,
                label: "DE",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 19,
                label: "DF",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 128,
                label: "DG",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 22,
                label: "DH",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 129,
                label: "DI",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 25,
                label: "DJ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 130,
                label: "DK",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 28,
                label: "DL",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 131,
                label: "DM",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 31,
                label: "DN",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 132,
                label: "DO",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 34,
                label: "DP",
                value: 0,
                width: widthRectangle + 14,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAF",
            value: 0,
            y: 0,
            col: [
              {
                key: 133,
                label: "DQ",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 134,
                label: "DR",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 135,
                label: "DS",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 136,
                label: "DT",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 137,
                label: "DU",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 138,
                label: "DV",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 139,
                label: "DW",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 140,
                label: "DX",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 141,
                label: "DY",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 142,
                label: "DZ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 143,
                label: "EA",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 144,
                label: "EB",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 145,
                label: "EC",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 146,
                label: "ED",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 147,
                label: "EE",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 148,
                label: "EF",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 149,
                label: "EG",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 150,
                label: "EH",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 151,
                label: "EI",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 152,
                label: "EJ",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 153,
                label: "EK",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 154,
                label: "EL",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                key: 155,
                label: "EM",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                key: 156,
                label: "EN",
                value: 0,
                width: widthRectangle + 14,
                height: 254,
                y: 0,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "BB",
    value: 1,
    height: 51,
    width: 942,
    x: 5,
    hoverPoints: {
      height: 58,
      y: -6,
    },
    col: [
      { label: "BBA", value: 0, height: 254, y: 0, key: 40 },
      { label: "BBB", value: 0, height: 254, y: 0, key: 41 },
      { label: "BBC", value: 0, height: 254, y: 0, key: 42 },
    ],
  },
  {
    label: "BC",
    value: 2,
    height: 64,
    width: 942,
    x: 5,
    col: [
      { label: "BCA", value: 0, height: 254, y: 0, key: 43 },
      { label: "BCB", value: 0, height: 254, y: 0, key: 45 },
      { label: "BCC", value: 0, height: 254, y: 0, key: 47 },
      { label: "BCD", value: 0, height: 254, y: 0, key: 48 },
      { label: "BCE", value: 0, height: 254, y: 0, key: 46 },
      { label: "BCF", value: 0, height: 254, y: 0, key: 44 },
    ],
  },
];

const mainRowC = [
  { label: "CA", value: 0, height: 80, y: 0, x: 0, key: 37 },
  { label: "CB", value: 1, height: 80, y: 80, x: 0, key: 38 },
  { label: "CC", value: 2, height: 80, y: 80 + 80, x: 0, key: 39 },
];

const polygonPoints = [
  { x: 0, y: 130 },
  { x: 26, y: 0 },
  { x: 62, y: 0 },
  { x: 62, y: 240 },
  { x: 26, y: 240 },
  { x: 0, y: 130 },
];

const polygonHoverPoints = [
  { x: 0, y: 130 },
  { x: 26, y: 0 },
  { x: 68, y: 0 },
  { x: 68, y: 240 },
  { x: 26, y: 240 },
  { x: 0, y: 130 },
];

const mainCols = [
  {
    label: "A",
    type: BoardColFigure.POLYGON,
    width: 62,
    height: 240,
    points: polygonPoints,
    hoverPoints: polygonHoverPoints,
    debugColor: 0x0000ff,
    debugOpacity: 0.5,
    key: 0,
  },
  {
    label: "B",
    type: BoardColFigure.RECTANGLE,
    width: 948,
    row: mainRowB,
    debugColor: 0x00ff00,
    debugOpacity: 0.2,
  },
  {
    label: "C",
    type: BoardColFigure.RECTANGLE,
    width: 79,
    height: 240,
    row: mainRowC,
    debugColor: 0x0000ff,
    debugOpacity: 0.3,
  },
];

export const drawerBoard: DrawerBoard = {
  x: -546.5,
  y: -174.5,
  width: 1091,
  height: 361,
  debugColor: 0xff0000,
  debugOpacity: 0.2,
  cols: mainCols,
};
