import { BoardColFigure, DrawerBoard } from "../types";

const generateRow = (start: number, end: number) => {
  const row = [];

  for (let i = start; i <= end; i++) {
    row.push({
      label: i.toString(),
      value: i,
    });
  }

  return row;
};

const firstRow = generateRow(0, 11);

const secondRow = [
  {
    label: "3",
    value: 3,
  },
  {
    label: "6",
    value: 6,
  },
  {
    label: "9",
    value: 9,
  },
  {
    label: "12",
    value: 12,
  },
  {
    label: "15",
    value: 15,
  },
  {
    label: "18",
    value: 18,
  },
  {
    label: "21",
    value: 21,
  },
  {
    label: "24",
    value: 24,
  },
  {
    label: "27",
    value: 27,
  },
  {
    label: "30",
    value: 30,
  },
  {
    label: "33",
    value: 33,
  },
  {
    label: "36",
    value: 36,
  },
];

const widthSquare = 17;
const widthRectangle = 61;

const mainRowB = [
  {
    label: "BA",
    value: 0,
    height: 246,
    x: 0,
    col: [
      {
        label: "BAA",
        value: 0,
        height: 0,
        y: 0,
        row: [
          {
            label: "BAAA",
            value: 0,
            height: 71,
            y: 0,
            col: [
              {
                label: "1",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "2",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "3",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "4",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "5",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "6",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "7",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "8",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "9",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "10",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "11",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "12",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "13",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "14",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "15",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "16",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "17",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "18",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "19",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "20",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "21",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "22",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "23",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "24",
                value: 0,
                width: widthRectangle + 16,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAB",
            value: 0,
            y: 0,
            col: [
              {
                label: "1",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "2",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "3",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "4",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "5",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "6",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "7",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "8",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "9",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "10",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "11",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "12",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "13",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "14",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "15",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "16",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "17",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "18",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "19",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "20",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "21",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "22",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "23",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "24",
                value: 0,
                width: widthRectangle + 16,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAC",
            value: 0,
            y: 0,
            col: [
              {
                label: "1",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "2",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "3",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "4",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "5",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "6",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "7",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "8",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "9",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "10",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "11",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "12",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "13",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "14",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "15",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "16",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "17",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "18",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "19",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "20",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "21",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "22",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "23",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "24",
                value: 0,
                width: widthRectangle + 16,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAD",
            value: 0,
            y: 0,
            col: [
              {
                label: "1",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "2",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "3",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "4",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "5",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "6",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "7",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "8",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "9",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "10",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "11",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "12",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "13",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "14",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "15",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "16",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "17",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "18",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "19",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "20",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "21",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "22",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "23",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "24",
                value: 0,
                width: widthRectangle + 16,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAE",
            value: 0,
            y: 0,
            col: [
              {
                label: "1",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "2",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "3",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "4",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "5",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "6",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "7",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "8",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "9",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "10",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "11",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "12",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "13",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "14",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "15",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "16",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "17",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "18",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "19",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "20",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "21",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "22",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "23",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "24",
                value: 0,
                width: widthRectangle + 16,
                height: 254,
                y: 0,
              },
            ],
          },
          {
            label: "BAAF",
            value: 0,
            y: 0,
            col: [
              {
                label: "1",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "2",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "3",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "4",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "5",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "6",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "7",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "8",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "9",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "10",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "11",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "12",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "13",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "14",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "15",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "16",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "17",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "18",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "19",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "20",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "21",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "22",
                value: 0,
                width: widthRectangle,
                height: 254,
                y: 0,
              },
              {
                label: "23",
                value: 0,
                width: widthSquare,
                height: 254,
                y: 0,
              },
              {
                label: "24",
                value: 0,
                width: widthRectangle + 16,
                height: 254,
                y: 0,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "BB",
    value: 1,
    height: 51,
    width: 942,
    x: 5,
    col: [
      { label: "BBA", value: 0, height: 254, y: 0 },
      { label: "BBB", value: 0, height: 254, y: 0 },
      { label: "BBC", value: 0, height: 254, y: 0 },
    ],
  },
  {
    label: "BC",
    value: 2,
    height: 64,
    width: 942,
    x: 5,
    col: [
      { label: "BCA", value: 0, height: 254, y: 0 },
      { label: "BCB", value: 0, height: 254, y: 0 },
      { label: "BCC", value: 0, height: 254, y: 0 },
      { label: "BCD", value: 0, height: 254, y: 0 },
      { label: "BCE", value: 0, height: 254, y: 0 },
      { label: "BCF", value: 0, height: 254, y: 0 },
    ],
  },
];

const mainRowC = [
  { label: "CA", value: 0, height: 80, y: 0, x: 0 },
  { label: "CB", value: 1, height: 80, y: 80, x: 0 },
  { label: "CC", value: 2, height: 80, y: 80 + 80, x: 0 },
];

const polygonPoints = [
  { x: 0, y: 130 },
  { x: 26, y: 0 },
  { x: 62, y: 0 },
  { x: 62, y: 240 },
  { x: 26, y: 240 },
  { x: 0, y: 130 },
];

const mainCols = [
  {
    label: "A",
    type: BoardColFigure.POLYGON,
    width: 62,
    height: 240,
    points: polygonPoints,
  },
  {
    label: "B",
    row: mainRowB,
    type: BoardColFigure.RECTANGLE,
    width: 948,
  },
  {
    label: "C",
    row: mainRowC,
    type: BoardColFigure.RECTANGLE,
    width: 79,
    height: 240,
  },
];

export const drawerBoard: DrawerBoard = {
  x: -546.5,
  y: -174.5,
  width: 1091,
  height: 361,
  debugColor: 0xff0000,
  debugOpacity: 0,
  cols: mainCols,
};
